apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      name: node-exporter
      labels:
        app: node-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9100"
    spec:
      containers:
        - name: node-exporter
          image: falmar/prom:node-exporter_v1
          args:
            - '--path.sysfs=/host/sys'
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/host/root'
            - '--collector.textfile.directory=/etc/node-exporter/'
            - '--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)'
            - '--collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$'
            - '--no-collector.ipvs'

          ports:
            - containerPort: 9100
          volumeMounts:
            - mountPath: /host/proc
              name: procs
              readOnly: true

            - mountPath: /host/sys
              name: sys
              readOnly: true

            - mountPath: /host/root
              mountPropagation: HostToContainer
              name: rootfs
              readOnly: true

            - mountPath: /etc/nodename
              name: hostname

      volumes:
        - name: procs
          hostPath:
            path: /proc

        - name: sys
          hostPath:
            path: /sys

        - name: rootfs
          hostPath:
            path: /

        - name: hostname
          hostPath:
            path: /etc/hostname
