{
 "title": "Kubernetes Pods",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "node", "query": "label_values(node_name)" },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage by PODs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node_name=~\"$node\", namespace=~\"$namespace\"}[$interval])) by (pod_name) * 100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node_name=~\"$node\", namespace=~\"$namespace\"}[$interval])) / sum(machine_cpu_cores{node_name=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Top 10 Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node_name=~\"$node\", namespace=~\"$namespace\"}[$interval])) by (pod_name, container_name)) * 100",
     "legendFormat": "{{container_name}}_{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by PODs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node_name=~\"$node\", namespace=~\"$namespace\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node_name=~\"$node\", namespace=~\"$namespace\"}) / sum(node_memory_MemTotal_bytes{node_name=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Top 10 Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",node_name=~\"$node\", namespace=~\"$namespace\"}) by (container_name, pod_name))",
     "legendFormat": "{{container_name}}_{{pod_name}}"
    }
   ]
  }
 ]
}