---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  serviceName: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      automountServiceAccountToken: true
      containers:
        - name: prom
          image: falmar/prom:prom_v1
          ports:
            - containerPort: 9090
---
