apiVersion: apps/v1
kind: Deployment
metadata:
  name: requesty
  namespace: default
  labels:
    app: requesty
spec:
  replicas: 3
  selector:
    matchLabels:
      app: requesty
  template:
    metadata:
      labels:
        app: requesty
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
    spec:
      containers:
        - name: server
          image: falmar/prom:requesty_v1
          env:
            - name: PORT
              value: "80"
          ports:
            - containerPort: 80
---
