---
apiVersion: v1
kind: Service
metadata:
  name: requesty
  namespace: default
  labels:
    app: requesty
spec:
  selector:
    app: requesty
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: requesty-cluster
  namespace: default
  labels:
    app: requesty
spec:
  selector:
    app: requesty
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
